# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - husky-zoom

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        env:
          SNOWPACK_PUBLIC_API_KEY: ${{ secrets.SNOWPACK_PUBLIC_API_KEY }}
          SNOWPACK_PUBLIC_AUTH_DOMAIN: ${{ secrets.SNOWPACK_PUBLIC_AUTH_DOMAIN }}
          SNOWPACK_PUBLIC_PROJECT_ID: ${{ secrets.SNOWPACK_PUBLIC_PROJECT_ID }}
          SNOWPACK_PUBLIC_DATABASE_URL: ${{ secrets.SNOWPACK_PUBLIC_DATABASE_URL }}
          SNOWPACK_PUBLIC_STORAGE_BUCKET: ${{ secrets.SNOWPACK_PUBLIC_STORAGE_BUCKET }}
          SNOWPACK_PUBLIC_MESSAGING_SENDER_ID: ${{ secrets.SNOWPACK_PUBLIC_MESSAGING_SENDER_ID }}
          SNOWPACK_PUBLIC_APP_ID: ${{ secrets.SNOWPACK_PUBLIC_APP_ID }}
          SNOWPACK_PUBLIC_MEASUREMENT_ID: ${{ secrets.SNOWPACK_PUBLIC_MEASUREMENT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          touch .env
          echo "SNOWPACK_PUBLIC_API_KEY=$SNOWPACK_PUBLIC_API_KEY" >> .env
          echo "SNOWPACK_PUBLIC_AUTH_DOMAIN=$SNOWPACK_PUBLIC_AUTH_DOMAIN" >> .env
          echo "SNOWPACK_PUBLIC_PROJECT_ID=$SNOWPACK_PUBLIC_PROJECT_ID" >> .env
          echo "SNOWPACK_PUBLIC_DATABASE_URL=$SNOWPACK_PUBLIC_DATABASE_URL" >> .env
          echo "SNOWPACK_PUBLIC_STORAGE_BUCKET=$SNOWPACK_PUBLIC_STORAGE_BUCKET" >> .env
          echo "SNOWPACK_PUBLIC_MESSAGING_SENDER_ID=$SNOWPACK_PUBLIC_MESSAGING_SENDER_ID" >> .env
          echo "SNOWPACK_PUBLIC_APP_ID=$SNOWPACK_PUBLIC_APP_ID" >> .env
          echo "SNOWPACK_PUBLIC_MEASUREMENT_ID=$SNOWPACK_PUBLIC_MEASUREMENT_ID" >> .env

          npm install
          npm run build --if-present
          echo $GOOGLE_APPLICATION_CREDENTIALS | >> dist/server/GOOGLE_APPLICATION_CREDENTIALS.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'husky-zoom'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ECC002E9F3CF4FB7AB41CD1DC9A21D48 }}
          package: .
